/**
 * Regenerates src/data/initialRecipes.js from TheMealDB (lookup by id).
 * Run: node scripts/build-seed.mjs
 * Every seed recipe is a real TheMealDB entry: real photo, ingredients, steps and source link.
 */
import fs from 'node:fs';
import { normalizeMeal } from '../server/mealNormalizer.js';

// Order matters: the first entry is the featured recipe on the landing page.
const SEED_IDS = [
  { id: 52963, category: 'Gourmet Mains' },               // Shakshuka
  { id: 52865, category: 'Gourmet Mains' },               // Matar Paneer
  { id: 52849, category: 'Artisanal Pastas' },            // Spinach & Ricotta Cannelloni
  { id: 52864, category: 'Artisanal Pastas' },            // Mushroom & Chestnut Rotolo
  { id: 52771, category: 'Artisanal Pastas' },            // Spicy Arrabiata Penne
  { id: 53067, category: 'Grain Bowls' },                 // Stuffed Bell Peppers with Quinoa and Black Beans
  { id: 52908, category: 'Gourmet Mains' },               // Ratatouille
  { id: 52854, category: 'Breakfast & Pastries' },        // Pancakes
  { id: 52909, category: 'Seasonal Desserts' }            // Tarte Tatin
];

// Hand-picked for the Shakshuka photo (TheMealDB 52963): egg yolk, cherry tomato, jalapeño slices.
const FEATURED_DETAILS = [
  { id: 'yolk', label: 'Egg yolk', x: 0.325, y: 0.345, zoom: 3.4 },
  { id: 'tomato', label: 'Cherry tomato', x: 0.785, y: 0.267, zoom: 3.6 },
  { id: 'chilli', label: 'Jalapeño', x: 0.575, y: 0.555, zoom: 4.2 }
];

const recipes = [];
const base = Date.now();
for (const [i, seed] of SEED_IDS.entries()) {
  const res = await fetch(`https://www.themealdb.com/api/json/v1/1/lookup.php?i=${seed.id}`);
  if (!res.ok) throw new Error(`TheMealDB lookup failed for ${seed.id}: ${res.status}`);
  const meal = (await res.json()).meals?.[0];
  if (!meal) throw new Error(`No TheMealDB entry for ${seed.id}`);
  recipes.push({
    ...normalizeMeal(meal),
    category: seed.category,
    isFavorite: false,
    createdAt: base - i * 60000
  });
}

const out = `// Generated by scripts/build-seed.mjs from TheMealDB (https://www.themealdb.com).
// Photos, ingredients and instructions belong to their TheMealDB contributors; see imageCredit / sourceUrl.
export const CATEGORIES = [
  'All',
  'Gourmet Mains',
  'Grain Bowls',
  'Artisanal Pastas',
  'Breakfast & Pastries',
  'Seasonal Desserts'
];

// The landing page features the first seed recipe.
export const FEATURED_RECIPE_ID = ${JSON.stringify(recipes[0].id)};

export const INITIAL_RECIPES = ${JSON.stringify(recipes, null, 2)};

// Close-up crops taken from the featured recipe's own photograph (x/y are fractions of the image).
// The landing hero shows them as small details beside the dish, so they always match it.
export const FEATURED_DETAILS = ${JSON.stringify(FEATURED_DETAILS, null, 2)};

// Seeds shipped before the move to sourced recipes. Untouched copies are dropped on load.
export const LEGACY_SEED_TITLES = {
  'recipe-risotto': 'Artisanal Saffron & Wild Porcini Risotto',
  'recipe-paneer-tikka': 'Royal Tandoori Paneer Tikka Skewers',
  'recipe-spinach-ravioli': 'Handmade Spinach & Ricotta Ravioli',
  'recipe-truffle-pasta': 'Truffle Tagliatelle with Wild Chanterelles',
  'recipe-grain-bowl': 'Mediterranean Quinoa Harvest Bowl',
  'recipe-pastries': 'Artisanal Butter Croissants & Cardamom Knots',
  'recipe-tart': 'Autumn Fig & Pistachio Ricotta Tart'
};

// AI-generated photographs that were bundled before; recipes still pointing at them get no image.
export const REMOVED_IMAGE_PATHS = [
  '/images/fresh-pastries.jpg',
  '/images/grain-bowl.jpg',
  '/images/hero-saffron-risotto.jpg',
  '/images/paneer-tikka.jpg',
  '/images/seasonal-dessert.jpg',
  '/images/spinach-ravioli.jpg',
  '/images/truffle-pasta.jpg'
];
`;
fs.writeFileSync(new URL('../src/data/initialRecipes.js', import.meta.url), out);
console.log('Wrote', recipes.length, 'recipes:', recipes.map((r) => r.title).join(' | '));
